Update issue templates
sjerzykiewicz/NoName-Surveys pull request #232
Opened 2024-11-28 21:12 UTC by sjerzykiewicz

2024-11-30 14:25 UTC, yanvoi requested changes

2024-11-30 14:25 UTC, yanvoi commented on .github/ISSUE_TEMPLATE/feature_request.md
> +A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
"A clear and concise description of what the problem is. e.g. I'm always frustrated when"*

2024-12-02 17:58 UTC, yanvoi approved these changes

2024-12-02 19:08 UTC, mtszlachetka approved these changes

2024-12-06 12:54 UTC, merged